const kleur = require("kleur")

console.log(kleur.red("red"))
console.log(kleur.green("green"))
console.log(kleur.yellow("yellow"))
console.log(kleur.blue("blue"))
console.log(kleur.magenta("magenta"))
console.log(kleur.bgWhite().black("bgWhite black"))
console.log(kleur.bgBlack().white("bgBlack white"))
console.log(kleur.bgBlack().gray("bgBlack gray"))
console.log(kleur.bgBlack().grey("bgBlack grey"))

console.log(kleur.bgBlack("bgBlack"))
console.log(kleur.bgRed("bgRed"))
console.log(kleur.bgGreen("bgGreen"))
console.log(kleur.bgYellow("bgYellow"))
console.log(kleur.bgBlue("bgBlue"))
console.log(kleur.bgMagenta("bgMagenta"))
console.log(kleur.bgWhite("bgWhite"))

console.log(kleur.bold("bold"))
console.log(kleur.bgBlue(`bgBlue and ${kleur.dim("dim")}`))
console.log(kleur.underline("underline"))
console.log(kleur.bgBlue(`bgBlue and ${kleur.inverse("inverse")}`))
console.log(kleur.strikethrough("strikethrough"))

console.log(kleur.cyan("cyan"))
console.log(kleur.bgCyan("bgCyan"))
console.log(kleur.italic("italic"))
console.log(kleur.bgBlue(`bgBlue and ${kleur.hidden("hidden")}`))
